-- Atlas 2 — Supabase/Postgres-skema.
-- Køres i Supabase SQL Editor (Dashboard -> SQL Editor -> New query -> kør denne fil).
-- 1:1-oversættelse af Atlas 1's Turso/libSQL-skema, se SCHEMA_MAPPING.md for begrundelse.

create table if not exists books (
  id               bigint generated by default as identity primary key,
  title            text not null,
  author           text not null default '',
  year             integer,
  isbn             text,
  cover_id         bigint,
  openlibrary_key  text,
  cover_data       text,
  source           text,
  needs_review     boolean not null default false,
  verified         boolean not null default false,
  notes            text,
  rating           text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

-- updated_at skal opdateres automatisk ved enhver ændring, uanset om skrivningen
-- sker via PostgREST PATCH, SQL Editor eller andet — dette var tidligere hardkodet
-- i Node-lagets updateBook()-funktion; nu er det databasens eget ansvar, hvilket
-- er mere robust (virker uanset hvilken klient der skriver).
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists books_set_updated_at on books;
create trigger books_set_updated_at
  before update on books
  for each row execute function set_updated_at();

-- Scaffold for fremtidige kulturtyper, videreført fra Atlas 1 (ingen UI/logik bygget endnu).
create table if not exists jumbo_books (
  id          bigint generated by default as identity primary key,
  title       text not null,
  number      integer not null,
  cover_data  text
);

create table if not exists comic_years (
  id          bigint generated by default as identity primary key,
  year        integer not null,
  cover_data  text
);

create table if not exists records (
  id                  bigint generated by default as identity primary key,
  title               text not null,
  artist              text,
  year                integer,
  discogs_release_id  bigint unique,
  cover_url           text
);

create table if not exists trips (
  id              bigint generated by default as identity primary key,
  destination     text not null,
  city            text,
  country         text,
  start_date      date,
  end_date        date,
  duration_days   integer,
  companions      text,
  notes           text,
  confidence      text,
  cover_data      text
);

-- Fremtidig krydsgående udvidelse (tags/favoritter på tværs af kulturtyper) — se SCHEMA_MAPPING.md.
-- Oprettes bevidst IKKE her endnu; tilføjes når første feature, der faktisk bruger den, bygges.

-- Vedligeholdelsesfunktion: retter auto-increment-tælleren for en tabel, hvis
-- den nogensinde kommer ud af trit med de faktiske id'er (fx efter en import
-- med eksplicitte id'er, se migrations/002_pre_real_data_import.sql). Ufarlig
-- at have liggende, selvom du aldrig får brug for den.
create or replace function reset_all_sequences()
returns void
language plpgsql
security definer
as $$
begin
  perform setval(pg_get_serial_sequence('books','id'),        coalesce((select max(id) from books), 1));
  perform setval(pg_get_serial_sequence('jumbo_books','id'),  coalesce((select max(id) from jumbo_books), 1));
  perform setval(pg_get_serial_sequence('comic_years','id'),  coalesce((select max(id) from comic_years), 1));
  perform setval(pg_get_serial_sequence('records','id'),      coalesce((select max(id) from records), 1));
  perform setval(pg_get_serial_sequence('trips','id'),        coalesce((select max(id) from trips), 1));
end;
$$;

grant execute on function reset_all_sequences() to authenticated;

-- ============================================================================
-- Row Level Security
--
-- Model: alle (også ikke-loggede-ind besøgende) kan LÆSE. Kun en logget-ind
-- bruger (Supabase Auth) kan oprette/redigere/slette. Dette er en direkte,
-- mere robust erstatning for Atlas 1's håndrullede password-gate — RLS
-- håndhæves af Postgres selv, ikke af applikationskode, og kan ikke omgås
-- ved at kalde et andet endpoint.
--
-- Supabase mapper automatisk enhver anmodning til én af to Postgres-roller:
--   - "anon"          når der ikke er noget gyldigt login (kun apikey-header)
--   - "authenticated" når der medsendes et gyldigt Supabase Auth-access-token
-- ============================================================================

alter table books enable row level security;

drop policy if exists "books_public_read" on books;
create policy "books_public_read"
  on books for select
  to anon, authenticated
  using (true);

drop policy if exists "books_authenticated_write" on books;
create policy "books_authenticated_write"
  on books for all
  to authenticated
  using (true)
  with check (true);

-- De fire scaffold-tabeller får samme politik nu, så de er klar når UI'en for
-- dem bygges — men de har ingen data endnu, og ingen kode læser/skriver dem.
alter table jumbo_books enable row level security;
drop policy if exists "jumbo_books_public_read" on jumbo_books;
create policy "jumbo_books_public_read" on jumbo_books for select to anon, authenticated using (true);
drop policy if exists "jumbo_books_authenticated_write" on jumbo_books;
create policy "jumbo_books_authenticated_write" on jumbo_books for all to authenticated using (true) with check (true);

alter table comic_years enable row level security;
drop policy if exists "comic_years_public_read" on comic_years;
create policy "comic_years_public_read" on comic_years for select to anon, authenticated using (true);
drop policy if exists "comic_years_authenticated_write" on comic_years;
create policy "comic_years_authenticated_write" on comic_years for all to authenticated using (true) with check (true);

alter table records enable row level security;
drop policy if exists "records_public_read" on records;
create policy "records_public_read" on records for select to anon, authenticated using (true);
drop policy if exists "records_authenticated_write" on records;
create policy "records_authenticated_write" on records for all to authenticated using (true) with check (true);

alter table trips enable row level security;
drop policy if exists "trips_public_read" on trips;
create policy "trips_public_read" on trips for select to anon, authenticated using (true);
drop policy if exists "trips_authenticated_write" on trips;
create policy "trips_authenticated_write" on trips for all to authenticated using (true) with check (true);

-- ============================================================================
-- Strammere variant (valgfri, IKKE aktiveret som standard):
-- Hvis du hellere vil begrænse skrivning til ÉN bestemt bruger (dit eget
-- Supabase Auth-uuid) fremfor "enhver der er logget ind", så erstat
-- "books_authenticated_write"-policyen med:
--
--   create policy "books_owner_write" on books for all to authenticated
--     using (auth.uid() = 'DIT-BRUGER-UUID-HER')
--     with check (auth.uid() = 'DIT-BRUGER-UUID-HER');
--
-- Find dit uuid i Supabase Dashboard -> Authentication -> Users.
-- Relevant hvis I nogensinde opretter en ekstra Auth-bruger (fx til en
-- familie-visning) som IKKE skal kunne redigere.
-- ============================================================================
