-- Atlas 2 — forberedelse før import af de RIGTIGE Atlas 1-data.
-- Køres ÉN GANG i Supabase SQL Editor, før du bruger tools/migrate_real_data.html.
--
-- Hvorfor nødvendig: 001_init.sql oprettede oprindeligt id-kolonnerne som
-- "GENERATED ALWAYS AS IDENTITY", som Postgres bevidst forhindrer i at få en
-- eksplicit værdi indsat udefra. Det er fint for helt nye rækker, men er i
-- vejen for at genindsætte dine rigtige bøger med deres oprindelige id'er fra
-- Turso (nødvendigt for at bevare 1:1-mapningen, jf. SCHEMA_MAPPING.md).
-- "GENERATED BY DEFAULT AS IDENTITY" løser det: id udfyldes automatisk som
-- før, men kan også sættes eksplicit, hvilket er præcis hvad importen gør.
-- (Opdaget og rettet ved at teste importværktøjet mod en lokal Postgres-kopi
-- FØR det blev kørt mod dine rigtige data — se ARCHITECTURE.md §6.)

alter table books        alter column id set generated by default;
alter table jumbo_books  alter column id set generated by default;
alter table comic_years  alter column id set generated by default;
alter table records      alter column id set generated by default;
alter table trips        alter column id set generated by default;

-- Efter en import med eksplicitte id'er "ved" auto-increment-tælleren
-- (sequence) ikke selv, at den skal springe de nye id'er over — den næste bog,
-- du opretter i appen uden selv at angive id, ville ellers kunne kollidere
-- med et af de lige importerede id'er ("duplicate key"-fejl). Denne funktion
-- retter det ved at sætte hver tabels tæller til dens nuværende max(id).
-- Kaldes automatisk af migrate_real_data.html som allersidste skridt, men er
-- ufarlig og genanvendelig at køre igen manuelt, hvis det nogensinde er nødvendigt.
create or replace function reset_all_sequences()
returns void
language plpgsql
security definer
as $$
begin
  perform setval(pg_get_serial_sequence('books','id'),        coalesce((select max(id) from books), 1));
  perform setval(pg_get_serial_sequence('jumbo_books','id'),  coalesce((select max(id) from jumbo_books), 1));
  perform setval(pg_get_serial_sequence('comic_years','id'),  coalesce((select max(id) from comic_years), 1));
  perform setval(pg_get_serial_sequence('records','id'),      coalesce((select max(id) from records), 1));
  perform setval(pg_get_serial_sequence('trips','id'),        coalesce((select max(id) from trips), 1));
end;
$$;

grant execute on function reset_all_sequences() to authenticated;
