-- Atlas 2 — "albumserier": ét fælles skema for nummererede albumsamlinger af
-- én (eller nogle få) faste kunstnere/forfattere — Tintin (Hergé) og Far Side
-- (Gary Larson) til at starte med.
--
-- Bevidst forskel fra §8 i docs/RUNNING.md's opskrift ("kopiér jumbo_books,
-- lav en ny tabel pr. samling"): Christian bad specifikt om ÉN fælles tabel
-- og ét fælles mønster for begge serier, netop så det er let at tilføje
-- flere lignende serier senere (fx Asterix) UDEN at oprette endnu en tabel
-- og endnu et sæt kopierede JS-funktioner hver gang — kun en ny række i
-- SERIES_DEFS i public/index.html og de tilhørende album-rækker herunder.
--
-- "series"-kolonnen er den delte nøgle mellem denne tabel og SERIES_DEFS i
-- public/index.html (fx 'tintin', 'farside') — den styrer hvilken fane et
-- album vises under, ligesom records.discogs_release_id styrer Plader.
--
-- unique(series, number): to album i SAMME serie kan ikke dele nummer (giver
-- ingen mening — det er selve rækkefølgen i serien) — men "0" er en gyldig
-- værdi (Tintin i Sovjetunionen er nr. 0, Far Sides "Prehistory"-bind er nr. 0),
-- og to FORSKELLIGE serier må gerne begge have et nr. 0, 1, 2 osv., så det er
-- IKKE en simpel unique(number) alene.

create table if not exists album_series (
  id          bigint generated by default as identity primary key,
  series      text not null,
  number      integer not null,
  title       text not null,
  author      text,
  year        integer,
  cover_data  text,
  cover_url   text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create unique index if not exists album_series_series_number_unique_idx
  on album_series (series, number);

drop trigger if exists album_series_set_updated_at on album_series;
create trigger album_series_set_updated_at
  before update on album_series
  for each row execute function set_updated_at();

-- Samme åbne læs/kun-login-kan-skrive-politik som resten af Atlas 2 (se
-- migrations/001_init.sql for begrundelsen).
alter table album_series enable row level security;

drop policy if exists "album_series_public_read" on album_series;
create policy "album_series_public_read"
  on album_series for select
  to anon, authenticated
  using (true);

drop policy if exists "album_series_authenticated_write" on album_series;
create policy "album_series_authenticated_write"
  on album_series for all
  to authenticated
  using (true)
  with check (true);

-- Hold reset_all_sequences() (se 001_init.sql/002_pre_real_data_import.sql)
-- opdateret, så den også dækker den nye tabel, hvis id-tælleren nogensinde
-- skal rettes efter en import med eksplicitte id'er.
create or replace function reset_all_sequences()
returns void
language plpgsql
security definer
as $$
begin
  perform setval(pg_get_serial_sequence('books','id'),         coalesce((select max(id) from books), 1));
  perform setval(pg_get_serial_sequence('jumbo_books','id'),   coalesce((select max(id) from jumbo_books), 1));
  perform setval(pg_get_serial_sequence('comic_years','id'),   coalesce((select max(id) from comic_years), 1));
  perform setval(pg_get_serial_sequence('records','id'),       coalesce((select max(id) from records), 1));
  perform setval(pg_get_serial_sequence('trips','id'),         coalesce((select max(id) from trips), 1));
  perform setval(pg_get_serial_sequence('album_series','id'),  coalesce((select max(id) from album_series), 1));
end;
$$;

grant execute on function reset_all_sequences() to authenticated;
