-- Atlas 2 — Rejser-modulet: udvider den eksisterende (uudnyttede) trips-tabel
-- fra 001_init.sql med rigtige felter, i stedet for at starte forfra.
--
-- trips indeholdt allerede 13 RIGTIGE rejser (migreret fra Atlas 1), aldrig
-- vist i nogen UI: destination, city, country, start_date, end_date,
-- duration_days, companions, notes, confidence, cover_data. Denne migration
-- bevarer alt det, tilføjer de nye felter Christian bad om, og fjerner kun
-- 'city' (erstattet af den relationelle trip_stops-tabel nedenfor, se
-- docs/RUNNING.md for begrundelsen: "gem ikke byer som kommasepareret tekst").
--
-- 'destination' omdøbes til 'title' (fri titel/navn på rejsen — de eksisterende
-- værdier, fx "Skotland (Highlands og Edinburgh)", er allerede gode titler).
-- 'duration_days', 'companions', 'confidence' og 'cover_data' røres IKKE —
-- de bruges bare ikke i v1's formular endnu (companions/cover_data er bevidst
-- fremtidigt scope, se docs/RUNNING.md §8).

alter table trips rename column destination to title;
alter table trips alter column title drop not null;

alter table trips add column if not exists status text not null default 'completed';
alter table trips add constraint trips_status_check
  check (status in ('completed', 'planned', 'wishlist'));

-- Bruges KUN når en præcis start/slutdato ikke kendes (typisk wishlist eller
-- gamle rejser man kun husker cirka). Findes start_date, udleder appen selv
-- år/måned af den i stedet for at gemme det samme to steder.
alter table trips add column if not exists year integer;
alter table trips add column if not exists month integer;
alter table trips add constraint trips_month_check check (month is null or month between 1 and 12);

alter table trips add column if not exists google_photos_url text;
alter table trips add column if not exists source text;

alter table trips add column if not exists created_at timestamptz not null default now();
alter table trips add column if not exists updated_at timestamptz not null default now();

drop trigger if exists trips_set_updated_at on trips;
create trigger trips_set_updated_at
  before update on trips
  for each row execute function set_updated_at(); -- samme delte funktion som resten af Atlas (se 001_init.sql)

-- Baglæns udfyldning af status for de 13 eksisterende rejser: en rejse hvor
-- slutdato (eller startdato, hvis slutdato mangler) allerede er passeret på
-- migrations-tidspunktet, sættes til 'completed' — resten til 'planned'.
-- Ingen af de 13 er wishlist (det konceptet fandtes ikke i Atlas 1).
update trips
set status = case
  when coalesce(end_date, start_date) is not null and coalesce(end_date, start_date) < current_date
    then 'completed'
  else 'planned'
end
where title is not null; -- dvs. alle eksisterende rækker; fremtidige inserts sætter selv status

-- ============================================================================
-- trip_stops — byer/steder på en rejse, som en rigtig relation i stedet for
-- en kommasepareret tekststreng i trips.city.
-- ============================================================================

create table if not exists trip_stops (
  id         bigint generated by default as identity primary key,
  trip_id    bigint not null references trips(id) on delete cascade,
  city       text not null,
  sort_order integer not null default 0
);

create index if not exists trip_stops_trip_id_idx on trip_stops(trip_id);

-- Migrér de eksisterende byer (fx "Edinburgh / Invergarry", "Thimpu, Paro,
-- Delhi") ind i trip_stops, splittet på "/" eller ",", FØR city-kolonnen
-- fjernes fra trips herunder.
insert into trip_stops (trip_id, city, sort_order)
select t.id, trim(s.city), s.ord - 1
from trips t
cross join lateral regexp_split_to_table(trim(t.city), '\s*/\s*|\s*,\s*') with ordinality as s(city, ord)
where t.city is not null and trim(t.city) <> '';

alter table trips drop column if exists city;

-- ============================================================================
-- Row Level Security — samme model som resten af Atlas: alle kan læse,
-- kun en logget-ind bruger kan skrive. trips har allerede sine policies fra
-- 001_init.sql (rører vi ikke); trip_stops får de samme her.
-- ============================================================================

alter table trip_stops enable row level security;

drop policy if exists "trip_stops_public_read" on trip_stops;
create policy "trip_stops_public_read"
  on trip_stops for select
  to anon, authenticated
  using (true);

drop policy if exists "trip_stops_authenticated_write" on trip_stops;
create policy "trip_stops_authenticated_write"
  on trip_stops for all
  to authenticated
  using (true)
  with check (true);

-- reset_all_sequences() (se 001_init.sql) skal også kende trip_stops, så
-- fremtidige rækker ikke kolliderer med id'er sat af denne migrations insert.
create or replace function reset_all_sequences()
returns void
language plpgsql
security definer
as $$
begin
  perform setval(pg_get_serial_sequence('books','id'),        coalesce((select max(id) from books), 1));
  perform setval(pg_get_serial_sequence('jumbo_books','id'),  coalesce((select max(id) from jumbo_books), 1));
  perform setval(pg_get_serial_sequence('comic_years','id'),  coalesce((select max(id) from comic_years), 1));
  perform setval(pg_get_serial_sequence('records','id'),      coalesce((select max(id) from records), 1));
  perform setval(pg_get_serial_sequence('trips','id'),        coalesce((select max(id) from trips), 1));
  perform setval(pg_get_serial_sequence('album_series','id'), coalesce((select max(id) from album_series), 1));
  perform setval(pg_get_serial_sequence('trip_stops','id'),   coalesce((select max(id) from trip_stops), 1));
end;
$$;

grant execute on function reset_all_sequences() to authenticated;
