-- Atlas 2 — Rejser-modulet, prioritet 6: review/import-arkitektur.
--
-- trip_candidates er "venteværelset" for rejser, som en fremtidig
-- opdagelses-mekanisme (Gmail/Google Photos, se docs/RUNNING.md §8 og
-- prioritet 7) foreslår, men som ALDRIG bliver til en rigtig rejse uden at
-- Christian aktivt godkender den her — se hans eksplicitte krav: "IKKE en
-- blind auto-import."
--
-- Samme grundprincip som bøgernes needs_review/verified-felter, men som sin
-- egen tabel i stedet for et par ekstra kolonner på trips, fordi en kandidat
-- har et andet livsforløb end en rigtig rejse (den kan afvises, flettes ind i
-- en eksisterende rejse, eller blive godkendt som en ny) og bærer data
-- (evidens, kilde-reference) som en rigtig rejse aldrig skal have.
--
-- suggested_cities er bevidst et simpelt text[] her — IKKE den samme
-- relationelle trip_stops-model som rigtige rejser bruger (se 005_trips.sql
-- og dens begrundelse "gem ikke byer som kommasepareret tekst"). Forskellen:
-- en kandidat er midlertidig, ustruktureret data under overvejelse, ikke en
-- rigtig registreret rejse endnu — den bliver først til rigtige trip_stops-
-- rækker, når Christian godkender den (se app-koden). At bygge en fuld
-- relationel model for data, der med overvejende sandsynlighed enten bliver
-- kasseret eller kopieret ind et andet sted, ville være unødig kompleksitet.

create table if not exists trip_candidates (
  id                       bigint generated by default as identity primary key,

  status                   text not null default 'pending'
                             check (status in ('pending', 'approved', 'rejected', 'merged')),

  suggested_title          text,
  suggested_country        text,
  suggested_cities         text[] not null default '{}',
  suggested_start_date     date,
  suggested_end_date       date,
  suggested_year           integer,
  suggested_month          integer check (suggested_month is null or suggested_month between 1 and 12),
  suggested_google_photos_url text,

  -- 'high' | 'medium' | 'low' — vises som badge i gennemgangs-UI'et, se
  -- Christians krav om en "confidence-indikator".
  confidence               text check (confidence is null or confidence in ('high', 'medium', 'low')),

  -- Bevis bag forslaget, til at Christian selv kan vurdere det — Christians
  -- krav: "vis evidensen". Array af objekter, fx:
  --   {"type":"email","summary":"Boardingpas CPH->NRT 14/3","date":"2027-03-14","link":"https://mail.google.com/..."}
  --   {"type":"google_photos_album","summary":"Album \"Japan foraar\", 42 billeder","date":"2027-03-14","link":"https://photos.google.com/..."}
  -- jsonb (ikke en egen evidens-tabel) fordi evidensen kun læses/vises samlet
  -- for netop denne kandidat, aldrig søges/filtreres selvstændigt på tværs af
  -- kandidater — en separat tabel ville være unødig kompleksitet her.
  evidence                 jsonb not null default '[]',

  -- Hvis opdagelsesmekanismen (eller Christian selv) genkender kandidaten som
  -- muligvis samme rejse som en allerede registreret rejse: Christians krav
  -- om "advarsel ved mulige dubletter".
  possible_duplicate_trip_id bigint references trips(id) on delete set null,

  -- Sat når status bliver 'approved' (rejsen kandidaten blev til) eller
  -- 'merged' (rejsen den blev flettet ind i) — til sporbarhed.
  linked_trip_id           bigint references trips(id) on delete set null,

  -- Hvor kandidaten kom fra, fx 'gmail' eller 'google_photos' (prioritet 7).
  source                   text,
  -- Kildens egen reference (fx Gmail thread-id, Google Photos album-id) —
  -- bruges af den fremtidige opdagelses-mekanisme til at undgå at foreslå
  -- den samme e-mail/det samme album igen, når den allerede er afvist eller
  -- godkendt. Ikke UNIQUE her (én rejse kan have flere kilde-referencer via
  -- flere e-mails), men bruges som opslag ved indsættelse.
  source_ref                text,

  reviewed_at               timestamptz,

  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now()
);

create index if not exists trip_candidates_status_idx on trip_candidates(status);
create index if not exists trip_candidates_source_ref_idx on trip_candidates(source_ref);

drop trigger if exists trip_candidates_set_updated_at on trip_candidates;
create trigger trip_candidates_set_updated_at
  before update on trip_candidates
  for each row execute function set_updated_at(); -- samme delte funktion som resten af Atlas

-- ============================================================================
-- Row Level Security — bevidst STRAMMERE end resten af Atlas.
--
-- Resten af Atlas (bøger, plader, rejser) er public read / login-required
-- write, fordi det er "vis frem"-data. trip_candidates indeholder derimod
-- uddrag af Christians private e-mails og fotoalbum-titler (evidensen), FØR
-- han har taget stilling til dem — det skal ikke være offentligt læsbart
-- bare fordi resten af Atlas er. Kun en logget-ind bruger (dvs. Christian)
-- kan læse eller skrive i denne tabel.
-- ============================================================================

alter table trip_candidates enable row level security;

drop policy if exists "trip_candidates_authenticated_all" on trip_candidates;
create policy "trip_candidates_authenticated_all"
  on trip_candidates for all
  to authenticated
  using (true)
  with check (true);

create or replace function reset_all_sequences()
returns void
language plpgsql
security definer
as $$
begin
  perform setval(pg_get_serial_sequence('books','id'),           coalesce((select max(id) from books), 1));
  perform setval(pg_get_serial_sequence('jumbo_books','id'),     coalesce((select max(id) from jumbo_books), 1));
  perform setval(pg_get_serial_sequence('comic_years','id'),     coalesce((select max(id) from comic_years), 1));
  perform setval(pg_get_serial_sequence('records','id'),         coalesce((select max(id) from records), 1));
  perform setval(pg_get_serial_sequence('trips','id'),           coalesce((select max(id) from trips), 1));
  perform setval(pg_get_serial_sequence('album_series','id'),    coalesce((select max(id) from album_series), 1));
  perform setval(pg_get_serial_sequence('trip_stops','id'),      coalesce((select max(id) from trip_stops), 1));
  perform setval(pg_get_serial_sequence('trip_candidates','id'), coalesce((select max(id) from trip_candidates), 1));
end;
$$;

grant execute on function reset_all_sequences() to authenticated;
