-- Atlas 2 — Events: koncerter, teater, opera, ballet, biograf og lignende.
--
-- Bevidst en SELVSTÆNDIG tabel og fane, ikke en undertype af Rejser: en rejse
-- er et forløb over flere dage med land og flere byer (trip_stops), mens en
-- event er ét tidspunkt på ét sted. At presse dem ind i samme tabel ville give
-- enten mange tomme felter (land/byer) eller en tabel, der skal rumme to ting.
-- Mønstret (planlagt -> oplevet via eksplicit bekræftelse, aldrig automatisk)
-- genbruges derimod fra Rejser, se isProbablyDone() i public/index.html.
--
-- 'source' er til en senere opdagelsesmekanisme (fx billetmails i Gmail via
-- samme kandidat-/review-mønster som trip_candidates) — bruges ikke endnu.

create table if not exists events (
  id          bigint generated by default as identity primary key,
  title       text not null,
  event_type  text not null default 'koncert',
  event_date  date not null,
  start_time  time,           -- valgfri: ikke alle events har et kendt tidspunkt
  end_time    time,
  venue       text,
  companions  text,           -- "Med hvem" som fri tekst, fx "Søren"
  ticket_count integer,
  notes       text,
  status      text not null default 'planned',
  source      text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  constraint events_type_check
    check (event_type in ('koncert', 'teater', 'opera', 'ballet', 'biograf', 'andet')),
  constraint events_status_check
    check (status in ('planned', 'attended')),
  constraint events_ticket_count_check
    check (ticket_count is null or ticket_count > 0)
  -- Bevidst INGEN check på end_time >= start_time: en koncert eller film kan
  -- slutte efter midnat (fx 23.00-01.00).
);

create index if not exists events_event_date_idx on events(event_date);

drop trigger if exists events_set_updated_at on events;
create trigger events_set_updated_at
  before update on events
  for each row execute function set_updated_at(); -- delt funktion, se 001_init.sql

-- Row Level Security — samme model som resten af Atlas: alle kan læse,
-- kun en logget-ind bruger kan skrive.
alter table events enable row level security;

drop policy if exists "events_public_read" on events;
create policy "events_public_read"
  on events for select
  to anon, authenticated
  using (true);

drop policy if exists "events_authenticated_write" on events;
create policy "events_authenticated_write"
  on events for all
  to authenticated
  using (true)
  with check (true);

-- reset_all_sequences() (se 001_init.sql / 005_trips.sql / 006_trip_candidates.sql)
-- skal også kende events — og må ikke tabe de tabeller, tidligere migrationer
-- allerede har tilføjet (trip_candidates).
create or replace function reset_all_sequences()
returns void
language plpgsql
security definer
as $$
begin
  perform setval(pg_get_serial_sequence('books','id'),        coalesce((select max(id) from books), 1));
  perform setval(pg_get_serial_sequence('jumbo_books','id'),  coalesce((select max(id) from jumbo_books), 1));
  perform setval(pg_get_serial_sequence('comic_years','id'),  coalesce((select max(id) from comic_years), 1));
  perform setval(pg_get_serial_sequence('records','id'),      coalesce((select max(id) from records), 1));
  perform setval(pg_get_serial_sequence('trips','id'),        coalesce((select max(id) from trips), 1));
  perform setval(pg_get_serial_sequence('album_series','id'), coalesce((select max(id) from album_series), 1));
  perform setval(pg_get_serial_sequence('trip_stops','id'),   coalesce((select max(id) from trip_stops), 1));
  perform setval(pg_get_serial_sequence('trip_candidates','id'), coalesce((select max(id) from trip_candidates), 1));
  perform setval(pg_get_serial_sequence('events','id'),       coalesce((select max(id) from events), 1));
end;
$$;

grant execute on function reset_all_sequences() to authenticated;
