-- Atlas 2 — Events: review/import-arkitektur (event_candidates).
--
-- Samme princip og form som trip_candidates (se 006_trip_candidates.sql):
-- "venteværelset" for events, som Gmail-opdagelsen (billetbekræftelser)
-- foreslår, men som ALDRIG bliver til en rigtig event uden at Christian
-- aktivt godkender den — Godkend / Redigér og godkend / Flet / Afvis.
--
-- Forskelle fra trip_candidates, alle fordi en event er ét tidspunkt:
--  * suggested_date er NULLABLE. Fx Billetlugens "dine billetter er klar"-mails
--    indeholder titlen men hverken dato eller sted — og mailens egen
--    afsendedato er IKKE eventens dato (billetter købes måneder i forvejen).
--    En kandidat uden dato kan derfor kun godkendes via "Redigér og godkend".
--  * Ingen byer/land/måned/år — kun én dato, evt. tidspunkt og sted.

create table if not exists event_candidates (
  id                       bigint generated by default as identity primary key,

  status                   text not null default 'pending'
                             check (status in ('pending', 'approved', 'rejected', 'merged')),

  suggested_title          text,
  suggested_event_type     text
                             check (suggested_event_type is null
                                    or suggested_event_type in ('koncert', 'teater', 'opera', 'ballet', 'biograf', 'andet')),
  suggested_date           date,
  suggested_start_time     time,
  suggested_venue          text,
  suggested_ticket_count   integer check (suggested_ticket_count is null or suggested_ticket_count > 0),

  -- 'high' | 'medium' | 'low' — vises som badge i gennemgangs-UI'et.
  confidence               text check (confidence is null or confidence in ('high', 'medium', 'low')),

  -- Bevis bag forslaget (vis evidensen): array af objekter, fx
  --   {"type":"email","summary":"Ticketmaster - Billetterne er dine! ...","date":"2026-02-13","link":"https://mail.google.com/..."}
  -- jsonb frem for en egen tabel af samme grund som hos trip_candidates.
  evidence                 jsonb not null default '[]',

  -- Christians krav (fra Rejser) om "advarsel ved mulige dubletter".
  possible_duplicate_event_id bigint references events(id) on delete set null,

  -- Sat når status bliver 'approved' (eventen kandidaten blev til) eller
  -- 'merged' (eventen den blev flettet ind i) — til sporbarhed.
  linked_event_id          bigint references events(id) on delete set null,

  source                   text,   -- fx 'gmail'
  -- Kildens egen reference (Gmail message-id'er, kommasepareret) — bruges til
  -- at undgå at foreslå samme mail igen, også når den er afvist/godkendt.
  source_ref               text,

  reviewed_at              timestamptz,

  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);

create index if not exists event_candidates_status_idx on event_candidates(status);
create index if not exists event_candidates_source_ref_idx on event_candidates(source_ref);

drop trigger if exists event_candidates_set_updated_at on event_candidates;
create trigger event_candidates_set_updated_at
  before update on event_candidates
  for each row execute function set_updated_at();

-- Row Level Security — STRAMMERE end resten af Atlas, præcis som trip_candidates:
-- evidensen er uddrag af Christians private e-mails (emnelinjer, links), FØR
-- han har taget stilling til dem, så kun en logget-ind bruger kan læse/skrive.
-- (Selve events er derimod offentligt læsbare, som resten af Atlas.)
alter table event_candidates enable row level security;

drop policy if exists "event_candidates_authenticated_all" on event_candidates;
create policy "event_candidates_authenticated_all"
  on event_candidates for all
  to authenticated
  using (true)
  with check (true);

create or replace function reset_all_sequences()
returns void
language plpgsql
security definer
as $$
begin
  perform setval(pg_get_serial_sequence('books','id'),            coalesce((select max(id) from books), 1));
  perform setval(pg_get_serial_sequence('jumbo_books','id'),      coalesce((select max(id) from jumbo_books), 1));
  perform setval(pg_get_serial_sequence('comic_years','id'),      coalesce((select max(id) from comic_years), 1));
  perform setval(pg_get_serial_sequence('records','id'),          coalesce((select max(id) from records), 1));
  perform setval(pg_get_serial_sequence('trips','id'),            coalesce((select max(id) from trips), 1));
  perform setval(pg_get_serial_sequence('album_series','id'),     coalesce((select max(id) from album_series), 1));
  perform setval(pg_get_serial_sequence('trip_stops','id'),       coalesce((select max(id) from trip_stops), 1));
  perform setval(pg_get_serial_sequence('trip_candidates','id'),  coalesce((select max(id) from trip_candidates), 1));
  perform setval(pg_get_serial_sequence('events','id'),           coalesce((select max(id) from events), 1));
  perform setval(pg_get_serial_sequence('event_candidates','id'), coalesce((select max(id) from event_candidates), 1));
end;
$$;

grant execute on function reset_all_sequences() to authenticated;
